# ConfigMap for backend
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---
# Deployment for backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
        - name: backend
          image: shashanka00315964/backend:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend

---
# Service for backend
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
